version: '3'
services:
  postgres_db:
    image: "postgres"
    volumes:
      - database-data:${VOLUME_PATH}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
volumes:
  database-data: