version: '3'
services:
  postgres_latest:
    image: "postgres"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres"]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - ./data/ctgov/:/data/ctgov/
      - ./scripts/ctgov:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}